### ISSUE TITLE
How do you add new languages?

### ISSUE THREAD

**Issue by DevNinjaa** [KABBOUCHI/simple-mvc#1]
How do you add new languages?

**Comment by KABBOUCHI** [comment]
You can create new folder in languages folder

![image](https://user-images.githubusercontent.com/9212274/34695720-86e1d8b6-f4d4-11e7-9007-1509b19a80ab.png)

you can switch language by using query parameter ``?lang=ar`` or by code ``config()->set('app.locale', 'ar');``
